### ISSUE TITLE
 Please correct this error, please.

### ISSUE THREAD

**Issue by alair069** [CaptainDuck/CommandOnHold#2]
Notice: Undefined index: items in C:\Users\Alair\Desktop\MEU SERVIDOR DE MINECRAFT 1.0.2 POCKETMINE\Genisys Servidor\plugins\CommandOnHold-master\src\CommandHold\Main.php on line 35

Warning: Invalid argument supplied for foreach() in C:\Users\Alair\Desktop\MEU SERVIDOR DE MINECRAFT 1.0.2 POCKETMINE\Genisys Servidor\plugins\CommandOnHold-master\src\CommandHold\Main.php on line 35

**Comment by CaptainDuck** [comment]
I'm working on this plugin in my device, once I finish it, I'll update the repository.
